version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: Asia/Shanghai
    versioning-strategy: increase
    open-pull-requests-limit: 100

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: Asia/Shanghai
