root: true

env:
  node: true
  es6: true

extends:
  - eslint:recommended
  - plugin:prettier/recommended

ignorePatterns:
  - dist/

parserOptions:
  parser: babel-eslint

overrides:
  - files:
      - "*.vue"

    extends:
      - plugin:vue/vue3-essential
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:prettier/recommended
      - "@vue/typescript/recommended"
      - "@vue/prettier"
      - "@vue/prettier/@typescript-eslint"

    plugins:
      - "@typescript-eslint"

    parser: vue-eslint-parser

    parserOptions:
      extraFileExtensions:
        - .vue
      parser: "@typescript-eslint/parser"
      ecmaVersion: 2020

    rules:
      "@typescript-eslint/explicit-function-return-type":
        - warn
        - allowTypedFunctionExpressions: true

      "@typescript-eslint/naming-convention":
        - warn
        - selector: default
          format:
            - camelCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - variable
          format:
            - camelCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - property
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: typeLike
          format:
            - PascalCase

      "@typescript-eslint/no-explicit-any":
        - warn
        - ignoreRestArgs: true

  - files:
      - "*.ts"

    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - plugin:prettier/recommended

    plugins:
      - "@typescript-eslint"

    parser: vue-eslint-parser

    parserOptions:
      parser: "@typescript-eslint/parser"
      project:
        - ./tsconfig.json
        - ./tests/e2e/tsconfig.json

    rules:
      "@typescript-eslint/explicit-function-return-type":
        - warn
        - allowTypedFunctionExpressions: true

      "@typescript-eslint/naming-convention":
        - warn
        - selector: default
          format:
            - camelCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - variable
          format:
            - camelCase
            - UPPER_CASE
            - PascalCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - property
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: typeLike
          format:
            - PascalCase

      "@typescript-eslint/no-explicit-any":
        - warn
        - ignoreRestArgs: true

      "@typescript-eslint/no-unsafe-member-access":
        - warn

  - files:
      - "**/tests/e2e/**/*.{j,t}s?(x)"
    env:
      cypress/globals: true
      mocha: true

    plugins:
      - cypress

    rules:
      strict: off

  - files:
      - "**/__tests__/*.{j,t}s?(x)"
      - "**/tests/unit/**/*.spec.{j,t}s?(x)"
    env:
      jest: true

    rules:
      "@typescript-eslint/no-explicit-any":
        - off
      "@typescript-eslint/no-unsafe-member-access":
        - off
